[package]
name = "objective_map_core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
petgraph = { version = "0.6.5", features = ["serde-1"] }
serde_json = "1.0"
rfd = "0.14.1"